# Generated by Django 3.0.3 on 2020-02-27 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sweet_id', models.IntegerField()),
                ('sweet_type', models.CharField(default=None, max_length=255)),
                ('sweet', models.CharField(default=None, max_length=255)),
                ('price', models.FloatField()),
                ('amount', models.FloatField()),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SweetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sweet_type', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=255)),
                ('password', models.CharField(default=None, max_length=255)),
                ('first_name', models.CharField(default=None, max_length=255)),
                ('last_name', models.CharField(default=None, max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(default=None, max_length=17)),
                ('address', models.CharField(default=None, max_length=255)),
                ('login', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sweet', models.CharField(default=None, max_length=255)),
                ('price', models.FloatField()),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sweets', to='candy_shop.SweetType')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(default='Guest', max_length=255)),
                ('first_name', models.CharField(default=None, max_length=255)),
                ('last_name', models.CharField(default=None, max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(default=None, max_length=17)),
                ('address', models.CharField(default=None, max_length=255)),
                ('order_date', models.DateTimeField()),
                ('delivery_date', models.DateTimeField()),
                ('comment', models.CharField(max_length=510, null=True)),
                ('order_info', models.CharField(max_length=2040)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='candy_shop.User')),
            ],
        ),
    ]
